source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'
gem 'spider-gazelle', github: 'cotag/spider-gazelle'

# Optional JSON codec (faster performance)
gem 'oj'

# Project requirements
gem 'rake'
gem 'uv-rays', github: 'cotag/uv-rays'
gem 'padrino-websockets', path: '../..'
# gem 'padrino-websockets', github: 'dariocravero/padrino-websockets'

# Component requirements
gem 'slim'

# Test requirements

# Padrino Stable Gem
# gem 'padrino', '0.12.0.rc3'

# Or Padrino Edge
gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.12.0.rc3'
# end
